spring:
  data:
    mongodb:
      uri: mongodb+srv://kundankumar199178:RKrRG2AbKSLHGTik@cluster0.n3ago.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: quizApp
      auto-index-creation: true

  logging:
    level:
      org:
        mongodb:
          driver: ERROR
      root: INFO
      com:
        example:
          QuizApp: DEBUG
  output:
    ansi:
      enabled: ALWAYS